---
resource_types:
  - name: vault
    type: docker-image
    source:
      repository: nullk/concourse-vault-resource
      tag: latest

resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/tkaburagi/vault-secure-ci-pipeline.git
    branch: master
- name: vault-secret-id
  type: vault
  icon: key-variant
  source:
    host: ((vault_addr))
    token: ((vault_init_token))
    secret: /kv/secret-id-concourse

jobs:
- name: pull-secret-id
  plan:
  - get: repo
    trigger: true
  - task: validate-vault-token
    file: repo/ci/validate-vault-token.yml
    params:
      VAULT_END_POINT: ((vault_addr))
      VAULT_INIT_TOKEN: ((vault_init_token))
  - task: pull-secret-id
    file: repo/ci/pull-secret-id.yml
    params:
      VAULT_END_POINT: ((vault_addr))
      VAULT_INIT_TOKEN: ((vault_init_token))
- name: tf-build
  plan:
  - get: repo
    trigger: true
    passed: [ pull-secret-id ]
  - get: vault-secret-id
  - task: generate-aws-secrets
    file: repo/ci/generate-aws-secrets.yml
    params:
      VAULT_END_POINT: ((vault_addr))
      VAULT_INIT_TOKEN: ((vault_init_token))
  - task: tf-fmt-init-plan
    file: repo/ci/tf-fmt-init-plan.yml
    params:
      VAULT_END_POINT: ((vault_addr))
      VAULT_INIT_TOKEN: ((vault_init_token))