
jobs:
- name: vault
  plan:
  - task: generate-secret
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu # Dockerイメージ名
          tag: bionic
      run:
        path: bash
        args: 
        - -c
        - |
          echo "Hello, world!"