
jobs:
- name: vault
  plan:
  - task: pull-secret-id
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: vault
          tag: latest
      params:
        VAULT_END_POINT: ((vault_addr))
        VAULT_INIT_TOKEN: ((vault_init_token))
      run:
        path: sh
        args:
        - -c
        - |
          vault -version

          # pulling vault secret id
          export VAULT_ADDR=${VAULT_END_POINT}
          vault login ${VAULT_INIT_TOKEN}
          vault status

  - task: generate-aws-secrets
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: vault # Dockerイメージ名
          tag: latest
      run:
        path: sh
        args:
          - -c
          - |
            echo "Hello, world!"