---
resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/tkaburagi/vault-secure-ci-pipeline.git
    branch: master

jobs:
- name: vault-pull-secret-id
  plan:
  - get: repo
    trigger: true
  - task: validate-vault-token
    file: repo/validate-vault-token.yml
    params:
      VAULT_END_POINT: ((vault_addr))
      VAULT_INIT_TOKEN: ((vault_init_token))
  - task: pull-secret-id
    file: repo/pull-secret-id.yml
    params:
      VAULT_END_POINT: ((vault_addr))
      VAULT_INIT_TOKEN: ((vault_init_token))

- name: terraform-plan
  plan:
  - get: repo
    trigger: true
    passed: [vault-pull-secret-id]
  - task: generate-aws-secrets
    file: repo/generate-aws-secrets.yml
    params:
      VAULT_END_POINT: ((vault_addr))
      VAULT_INIT_TOKEN: ((vault_init_token))
